### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by dover20** [IlIllII/collecobrary#17]
The [https://curated-courses.herokuapp.com](https://curated-courses.herokuapp.com) home page is saying "Application Error".

**Comment by IlIllII** [comment]
Oh no! 😢

Thanks for alerting me to this. I'll troubleshoot this evening or tomorrow and get it straightened out.

Let me know if you have any other thoughts, ideas, criticisms, issues, praise, etc. 😄

**Comment by IlIllII** [comment]
@dover20 Heroku turned off my free dyno. 😠 

I fixed it and the site should now be up and running at [shapesofknowledge.io](https://shapesofknowledge.io)

<img width="229" alt="image" src="https://user-images.githubusercontent.com/78166995/210895326-60b0672f-6341-4a57-a695-8049347e8232.png">

I'll update the GitHub project information too.

**Comment by dover20** [comment]
Sweet! The roadmaps are awesome. I think Shapes of Knowledge is a more fitting name too.
